In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
![ChessUrl](https://media.giphy.com/media/fkrV5Oacwjduw/giphy.gif, "shaq")

/bin/sh: -c: line 0: syntax error near unexpected token `https://media.giphy.com/media/fkrV5Oacwjduw/giphy.gif,'
/bin/sh: -c: line 0: `[ChessUrl](https://media.giphy.com/media/fkrV5Oacwjduw/giphy.gif, "shaq")'

# 1. opening the file and decoding it into a pandas data frame.

In [3]:
df = pd.read_csv("GSAF5.csv", encoding = "latin1")

# 2. inspecting the data frame.

In [4]:
pd.set_option('display.max_columns', 6000)
# "The maximum width in characters of a column"
pd.set_option('display.max_colwidth', 500)

In [5]:
df.count()

Case Number               5992
Date                      5992
Year                      5992
Type                      5992
Country                   5949
Area                      5590
Location                  5496
Activity                  5465
Name                      5792
Sex                       5425
Age                       3311
Injury                    5965
Fatal (Y/N)               5973
Time                      2779
Species                   3058
Investigator or Source    5977
pdf                       5992
href formula              5991
href                      5989
Case Number.1             5992
Case Number.2             5992
original order            5992
Unnamed: 22                  1
Unnamed: 23                  2
dtype: int64

In [6]:
df.head()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,16,Minor injury to thigh,N,13h00,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.c-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2016.09.18.c-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2016.09.18.c-NSB.pdf,2016.09.18.c,2016.09.18.c,5993,NaN,NaN
1,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Chucky Luciano,M,36,Lacerations to hands,N,11h00,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.b-Luciano.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2016.09.18.b-Luciano.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2016.09.18.b-Luciano.pdf,2016.09.18.b,2016.09.18.b,5992,NaN,NaN
2,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,43,Lacerations to lower leg,N,10h43,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2016.09.18.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2016.09.18.a-NSB.pdf,2016.09.18.a,2016.09.18.a,5991,NaN,NaN
3,2016.09.17,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,Rory Angiolella,M,NaN,Struck by fin on chest & leg,N,NaN,NaN,"The Age, 9/18/2016",2016.09.17-Angiolella.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2016.09.17-Angiolella.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2016.09.17-Angiolella.pdf,2016.09.17,2016.09.17,5990,NaN,NaN
4,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,male,M,NaN,No injury: Knocked off board by shark,N,NaN,2 m shark,"The Age, 9/16/2016",2016.09.16-BellsBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2016.09.16-BellsBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2016.09.16-BellsBeach.pdf,2016.09.16,2016.09.15,5989,NaN,NaN

# 3. droping the last two cloums:(unnamed: 22 and unamed 23)

In [7]:
df["Unnamed: 22"].value_counts()

stopped here    1
Name: Unnamed: 22, dtype: int64

In [8]:
df["Unnamed: 23"].value_counts()

change filename    1
Teramo             1
Name: Unnamed: 23, dtype: int64

In [9]:
df.loc[df['Unnamed: 23'] == "Teramo"]

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
4182,1952.07.13,13-Jul-52,1952,Provoked,USA,California,"San Diego, San Diego County",Fishing,"Gerald Howard, on board sportsfishing boat Teresa A",M,34,Part of hand removed by shark he had caught PROVOKED INCIDENT,N,NaN,NaN,"L.A. Times, 7/14/1952",1952.07.13-Howard.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/1952.07.13-Howard.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/1952.07.13-Howard.pdf,1952.07.13,1952.07.13,1811,NaN,Teramo

In [10]:
df.loc[df['Case Number'] == "2006.06.18"]

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
1247,2006.06.18,18-Jun-06,2006,Unprovoked,BRAZIL,Pernambuco,"Punta Del Chifre Beach, Olinda",Body boarding,Humberto Pessoa Batista,M,27,Left thigh bitten FATAL,Y,09h00,NaN,globalsurfnews.com,2006.06.18-Batista.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2006.06.18-Batista.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2006.06.18-Batista.pdf,2006.06.18,2006.06.18,4746,stopped here,NaN

In [11]:
df = df.drop( labels = ["Unnamed: 23", "Unnamed: 22"], axis = 1)

# 4. reinnxing and rewriting original order columns

In [12]:
df =df[::-1]

In [13]:
df

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order
5991,ND.0001,1845-1853,0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away the lower extremities""",Y,NaN,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_directoryND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_directoryND-0001-Ceylon.pdf,ND.0001,ND.0001,2
5990,ND.0002,1883-1889,0,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,Jules Patterson,M,NaN,FATAL,Y,NaN,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/ND-0002-JulesPatterson.pdf,ND.0002,ND.0002,3
5989,ND.0003,1900-1905,0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,NaN,FATAL,Y,NaN,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/ND-0003-Ocracoke_1900-1905.pdf,ND.0003,ND.0003,4
5988,ND.0004,Before 1903,0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/ND-0004-Ahmun.pdf,ND.0004,ND.0004,5
5987,ND.0005,Before 1903,0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/ND-0005-RoebuckBay.pdf,ND.0005,ND.0005,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,male,M,NaN,No injury: Knocked off board by shark,N,NaN,2 m shark,"The Age, 9/16/2016",2016.09.16-BellsBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2016.09.16-BellsBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2016.09.16-BellsBeach.pdf,2016.09.16,2016.09.15,5989
3,2016.09.17,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,Rory Angiolella,M,NaN,Struck by fin on chest & leg,N,NaN,NaN,"The Age, 9/18/2016",2016.09.17-Angiolella.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2016.09.17-Angiolella.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2016.09.17-Angiolella.pdf,2016.09.17,2016.09.17,5990
2,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,43,Lacerations to lower leg,N,10h43,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2016.09.18.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2016.09.18.a-NSB.pdf,2016.09.18.a,2016.09.18.a,5991
1,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Chucky Luciano,M,36,Lacerations to hands,N,11h00,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.b-Luciano.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2016.09.18.b-Luciano.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2016.09.18.b-Luciano.pdf,2016.09.18.b,2016.09.18.b,5992
0,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,16,Minor injury to thigh,N,13h00,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.c-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2016.09.18.c-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2016.09.18.c-NSB.pdf,2016.09.18.c,2016.09.18.c,5993

In [14]:
df = df.reset_index(drop = True).drop(labels = "original order", axis = 1)

In [15]:
df.index = df.index +1 
df.index.name = "Orginal_Order"

In [16]:
df

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2
Orginal_Order,,,,,,,,,,,,,,,,,,,,,
1,ND.0001,1845-1853,0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away the lower extremities""",Y,NaN,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_directoryND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_directoryND-0001-Ceylon.pdf,ND.0001,ND.0001
2,ND.0002,1883-1889,0,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,Jules Patterson,M,NaN,FATAL,Y,NaN,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/ND-0002-JulesPatterson.pdf,ND.0002,ND.0002
3,ND.0003,1900-1905,0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,NaN,FATAL,Y,NaN,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/ND-0003-Ocracoke_1900-1905.pdf,ND.0003,ND.0003
4,ND.0004,Before 1903,0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/ND-0004-Ahmun.pdf,ND.0004,ND.0004
5,ND.0005,Before 1903,0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/ND-0005-RoebuckBay.pdf,ND.0005,ND.0005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5988,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,male,M,NaN,No injury: Knocked off board by shark,N,NaN,2 m shark,"The Age, 9/16/2016",2016.09.16-BellsBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2016.09.16-BellsBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2016.09.16-BellsBeach.pdf,2016.09.16,2016.09.15
5989,2016.09.17,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,Rory Angiolella,M,NaN,Struck by fin on chest & leg,N,NaN,NaN,"The Age, 9/18/2016",2016.09.17-Angiolella.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2016.09.17-Angiolella.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2016.09.17-Angiolella.pdf,2016.09.17,2016.09.17
5990,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,43,Lacerations to lower leg,N,10h43,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2016.09.18.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2016.09.18.a-NSB.pdf,2016.09.18.a,2016.09.18.a
5991,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Chucky Luciano,M,36,Lacerations to hands,N,11h00,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.b-Luciano.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2016.09.18.b-Luciano.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2016.09.18.b-Luciano.pdf,2016.09.18.b,2016.09.18.b
5992,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,16,Minor injury to thigh,N,13h00,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.c-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2016.09.18.c-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2016.09.18.c-NSB.pdf,2016.09.18.c,2016.09.18.c

# 5. eliminating duplicates (in cases columns)
only 11 cases had diffrent values no need to keep 3 columns, best to elimante 2 columns

In [17]:
df.count()

Case Number               5992
Date                      5992
Year                      5992
Type                      5992
Country                   5949
Area                      5590
Location                  5496
Activity                  5465
Name                      5792
Sex                       5425
Age                       3311
Injury                    5965
Fatal (Y/N)               5973
Time                      2779
Species                   3058
Investigator or Source    5977
pdf                       5992
href formula              5991
href                      5989
Case Number.1             5992
Case Number.2             5992
dtype: int64

In [18]:
df = df.drop( labels = ["Case Number.1", "Case Number.2"], axis = 1)

# 6. Source column: href formula, herf pdf.
keeping on the herf

In [19]:
df.count()

Case Number               5992
Date                      5992
Year                      5992
Type                      5992
Country                   5949
Area                      5590
Location                  5496
Activity                  5465
Name                      5792
Sex                       5425
Age                       3311
Injury                    5965
Fatal (Y/N)               5973
Time                      2779
Species                   3058
Investigator or Source    5977
pdf                       5992
href formula              5991
href                      5989
dtype: int64

In [20]:

  df
# filtering data 
#test1 = df.where(df["Source"]!=np.nan, inplace = True)

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href
Orginal_Order,,,,,,,,,,,,,,,,,,,
1,ND.0001,1845-1853,0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away the lower extremities""",Y,NaN,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_directoryND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_directoryND-0001-Ceylon.pdf
2,ND.0002,1883-1889,0,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,Jules Patterson,M,NaN,FATAL,Y,NaN,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/ND-0002-JulesPatterson.pdf
3,ND.0003,1900-1905,0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,NaN,FATAL,Y,NaN,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/ND-0003-Ocracoke_1900-1905.pdf
4,ND.0004,Before 1903,0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/ND-0004-Ahmun.pdf
5,ND.0005,Before 1903,0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/ND-0005-RoebuckBay.pdf
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5988,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,male,M,NaN,No injury: Knocked off board by shark,N,NaN,2 m shark,"The Age, 9/16/2016",2016.09.16-BellsBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2016.09.16-BellsBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2016.09.16-BellsBeach.pdf
5989,2016.09.17,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,Rory Angiolella,M,NaN,Struck by fin on chest & leg,N,NaN,NaN,"The Age, 9/18/2016",2016.09.17-Angiolella.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2016.09.17-Angiolella.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2016.09.17-Angiolella.pdf
5990,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,43,Lacerations to lower leg,N,10h43,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2016.09.18.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2016.09.18.a-NSB.pdf
5991,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Chucky Luciano,M,36,Lacerations to hands,N,11h00,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.b-Luciano.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2016.09.18.b-Luciano.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2016.09.18.b-Luciano.pdf
5992,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,16,Minor injury to thigh,N,13h00,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.c-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2016.09.18.c-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2016.09.18.c-NSB.pdf

In [21]:
test1 = df.loc

In [22]:
df[df["href formula"].isnull()]

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href
Orginal_Order,,,,,,,,,,,,,,,,,,,
2973,1975.01.19,19-Jan-75,1975,Unprovoked,AUSTRALIA,South Australia,Coffin Bay,Surfing,David Barrowman,M,17,"FATAL, body not recovered",Y,NaN,NaN,"J. West; Adelaide Advertiser, 1/20/1975; P. Kemp, GSAF",1975.01.19-Barrowman.pdf,NaN,http://sharkattackfile.net/spreadsheets/pdf_directory/1975.01.19-Barrowman.pdf

In [23]:
df[df["href"].isnull()]

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href
Orginal_Order,,,,,,,,,,,,,,,,,,,
306,1864.01.02,02-Jan-1864,1864,Unprovoked,NEW ZEALAND,North Island,"Brickfield Bay, Auckland Harbour",Standing / Bathing,Mr. Kelsall,M,NaN,Minor injury to hip,N,NaN,NaN,"Wellington Independent, 1/21/1864",1864.01.01-Kelsall.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/1864.01.01-Kelsall.pdf,NaN
3718,1993.04.00,Apr-93,1993,Invalid,AUSTRALIA,Tasmania,Barren Joey Island,Spearfishing,Tony Szolomiak,M,32,No inujury,N,NaN,NaN,"C. Black & T. Peake, GSAF",1993.04.00-Szolomiak.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/1993.04.00-Szolomiak.pdf,NaN
5799,2015.06.13,13-Jun-15,2015,Unprovoked,USA,California,Off San Diego,NaN,Elke Specker,F,NaN,Severe laceration to leg,N,NaN,Mako shark,"Courthouse News Service, 11/18/2015",Court Case pending,http://sharkattackfile.net/spreadsheets/pdf_directory/Court Case pending,NaN

In [24]:
df = df.drop(labels = ["href formula", "href"], axis = 1)

# 7.Table head names clean and rename

In [25]:
heads = list(df.columns)
heads

['Case Number',
 'Date',
 'Year',
 'Type',
 'Country',
 'Area',
 'Location',
 'Activity',
 'Name',
 'Sex ',
 'Age',
 'Injury',
 'Fatal (Y/N)',
 'Time',
 'Species ',
 'Investigator or Source',
 'pdf']

In [26]:
df.rename(columns={'Sex ':'Sex',
                          'Fatal (Y/N)':'Fatal',
                          'Species ':'Species',
                  "Investigator or Source" : "Investigator_or_Source",
                  "Case Number" : "Case_Number",
                  "pdf" : "Source"}, 
                 inplace=True)

In [27]:
df.columns

Index(['Case_Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Location',
       'Activity', 'Name', 'Sex', 'Age', 'Injury', 'Fatal', 'Time', 'Species',
       'Investigator_or_Source', 'Source'],
      dtype='object')

# 8. alimentating ambiguities in dataframe (Type, Fatal, Country)

# I Type

In [28]:
df[(df["Country"] == "GREECE") & (df["Fatal"] == "Y") & (df["Species"])]

,Case_Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal,Time,Species,Investigator_or_Source,Source
Orginal_Order,,,,,,,,,,,,,,,,,
1683,1948.09.22,22-Sep-48,1948,Unprovoked,GREECE,Attica,Keratsini,Swimming,Dimitris Parassakis,M,17,FATAL,Y,16h00,Said to be 6.4 m [21'] shark,"C. Moore, GSAF",1948.09.22-Parasakis.pdf
1782,1951.08.17.a,17-Aug-51,1951,Unprovoked,GREECE,Corfu Island,Off Royal Residence,Swimming,Vanda Pierri,F,16,"FATAL, body not recovered Another man was also injured by the shark at same time (see below)",Y,NaN,White shark,A De Maddalena,1951.08.17.a-Perri.pdf
1951,1956.00.00.f,1956,1956,Unprovoked,GREECE,Corfu Island,Kérkira,Swimming off yacht,Margoulis,F,15,FATAL,Y,NaN,White shark,MEDSAF,1956.00.00.f-Margoulis.pdf
2470,1963.06.01.b,01-Jun-63,1963,Unprovoked,GREECE,Thessaly,near Trikerion Island,Swimming,Helga Pogl,F,42,FATAL,Y,16h30,"White shark, 3 m",A. De Maddalena,1963.06.01.b-Pogl.pdf

In [29]:
df['Date'].value_counts()

1957           11
1942            9
1956            8
1941            7
1950            7
               ..
04-May-11       1
13-Apr-1898     1
13-Jan-80       1
27-Jun-05       1
07-Jan-46       1
Name: Date, Length: 5128, dtype: int64

In [30]:
df.dtypes

Case_Number               object
Date                      object
Year                       int64
Type                      object
Country                   object
Area                      object
Location                  object
Activity                  object
Name                      object
Sex                       object
Age                       object
Injury                    object
Fatal                     object
Time                      object
Species                   object
Investigator_or_Source    object
Source                    object
dtype: object

In [31]:
df.head()

,Case_Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal,Time,Species,Investigator_or_Source,Source
Orginal_Order,,,,,,,,,,,,,,,,,
1,ND.0001,1845-1853,0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away the lower extremities""",Y,NaN,NaN,S.W. Baker,ND-0001-Ceylon.pdf
2,ND.0002,1883-1889,0,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,Jules Patterson,M,NaN,FATAL,Y,NaN,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf
3,ND.0003,1900-1905,0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,NaN,FATAL,Y,NaN,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf
4,ND.0004,Before 1903,0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf
5,ND.0005,Before 1903,0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf

In [32]:
df["Type"].value_counts()

Unprovoked      4386
Provoked         557
Invalid          519
Sea Disaster     220
Boat             200
Boating          110
Name: Type, dtype: int64

In [33]:
test = df["Type"].replace(["Boating"], ["Boat"])

In [34]:
test.value_counts()

Unprovoked      4386
Provoked         557
Invalid          519
Boat             310
Sea Disaster     220
Name: Type, dtype: int64

In [35]:
df["Type"] = test

In [36]:
df["Type"].value_counts()

Unprovoked      4386
Provoked         557
Invalid          519
Boat             310
Sea Disaster     220
Name: Type, dtype: int64

## II Fatal

In [37]:
df["Fatal"].value_counts()

N          4315
Y          1552
UNKNOWN      94
 N            8
N             1
F             1
n             1
#VALUE!       1
Name: Fatal, dtype: int64

In [38]:
test = df["Fatal"].replace([" N", 'F', 'N ', 'n', "#VALUE!"], 
                                 ["N", 'Y', 'N', 'N', 'UNKNOWN'])

In [39]:
test.value_counts()

N          4325
Y          1553
UNKNOWN      95
Name: Fatal, dtype: int64

In [40]:
df["Fatal"] = test

In [41]:
df["Fatal"].value_counts()

N          4325
Y          1553
UNKNOWN      95
Name: Fatal, dtype: int64

## III Country

In [42]:
test = df["Country"].replace([" TONGA", "EGYPT ", " PHILIPPINES", "CEYLON (SRI LANKA)", "EGYPT / ISRAEL", "UNITED ARAB EMIRATES (UAE)"],
                             ['TONGA', "EGYPT", "PHILIPPINES", "SRI LANKA", "EGYPT", "UNITED ARAB EMIRATES" ]).str.upper()

In [43]:
pd.set_option('display.max_rows', 5400)
test.value_counts()

USA                               2116
AUSTRALIA                         1279
SOUTH AFRICA                       565
PAPUA NEW GUINEA                   133
NEW ZEALAND                        125
BRAZIL                             102
BAHAMAS                             98
MEXICO                              81
ITALY                               71
FIJI                                65
PHILIPPINES                         60
REUNION                             57
NEW CALEDONIA                       51
MOZAMBIQUE                          44
CUBA                                42
SPAIN                               40
EGYPT                               39
INDIA                               37
CROATIA                             34
JAPAN                               32
PANAMA                              32
IRAN                                29
SOLOMON ISLANDS                     29
GREECE                              25
HONG KONG                           24
JAMAICA                             23
FRENCH POLYNESIA                    22
INDONESIA                           20
ENGLAND                             19
TONGA                               18
PACIFIC OCEAN                       17
BERMUDA                             16
ATLANTIC OCEAN                      16
SRI LANKA                           14
VANUATU                             14
VIETNAM                             14
FRANCE                              13
MARSHALL ISLANDS                    13
COSTA RICA                          12
SOUTH ATLANTIC OCEAN                12
IRAQ                                12
TURKEY                              12
SENEGAL                             11
VENEZUELA                           11
KENYA                               10
CANADA                              10
NEW GUINEA                          10
UNITED KINGDOM                      10
TAIWAN                               9
COLUMBIA                             9
SIERRA LEONE                         9
TANZANIA                             8
SCOTLAND                             8
SEYCHELLES                           8
CHILE                                8
ECUADOR                              8
CARIBBEAN SEA                        8
SOUTH KOREA                          8
MAURITIUS                            7
DOMINICAN REPUBLIC                   7
NORTH PACIFIC OCEAN                  7
INDIAN OCEAN                         7
MADAGASCAR                           7
ISRAEL                               7
YEMEN                                7
SAMOA                                7
OKINAWA                              6
CHINA                                6
SOMALIA                              6
NEW BRITAIN                          6
SINGAPORE                            6
NICARAGUA                            6
THAILAND                             6
KIRIBATI                             6
TURKS & CAICOS                       5
SAUDI ARABIA                         5
MALTA                                5
MID ATLANTIC OCEAN                   5
BARBADOS                             5
LIBYA                                5
PALAU                                5
AZORES                               5
EL SALVADOR                          4
RUSSIA                               4
BURMA                                4
MALAYSIA                             4
GUAM                                 4
NIGERIA                              4
PERSIAN GULF                         4
NORTH ATLANTIC OCEAN                 4
GRENADA                              4
SUDAN                                4
HAITI                                3
UNITED ARAB EMIRATES                 3
BELIZE                               3
CAPE VERDE                           3
PORTUGAL                             3
HONDURAS                             3
AMERICAN SAMOA                       3
LEBANON                              3
MICRONESIA                           3
LIBERIA                              3
TUNISIA                              3
MONTENEGRO                           3
GUINEA                               3
URUGUAY                              3
TRINIDAD & TOBAGO                    3
YEMEN                                2
PACIFIC OCEAN                        2
CRETE                                2
JOHNSTON ISLAND                      2
SOUTHWEST PACIFIC OCEAN              2
NAMIBIA                              2
NORWAY                               2
MEDITERRANEAN SEA                    2
CAYMAN ISLANDS                       2
SOUTH PACIFIC OCEAN                  2
CENTRAL PACIFIC                      2
SLOVENIA                             1
ICELAND                              1
BAHREIN                              1
NICARAGUA                            1
GHANA                                1
WESTERN SAMOA                        1
RED SEA / INDIAN OCEAN               1
COAST OF AFRICA                      1
SOUTH CHINA SEA                      1
SYRIA                                1
DJIBOUTI                             1
GREENLAND                            1
THE BALKANS                          1
ITALY / CROATIA                      1
ASIA?                                1
MEDITERRANEAN SEA?                   1
ST HELENA                            1
MEXICO                               1
ALGERIA                              1
BRITISH WEST INDIES                  1
IRAN / IRAQ                          1
EQUATORIAL GUINEA / CAMEROON         1
MONACO                               1
RED SEA?                             1
BRITISH VIRGIN ISLANDS               1
ST. MAARTIN                          1
ADMIRALTY ISLANDS                    1
TASMAN SEA                           1
GRAND CAYMAN                         1
SWEDEN                               1
NORTH ATLANTIC OCEAN                 1
PALESTINIAN TERRITORIES              1
KOREA                                1
ANDAMAN / NICOBAR ISLANDAS           1
ST. MARTIN                           1
GUYANA                               1
MARTINIQUE                           1
BRITISH ISLES                        1
DIEGO GARCIA                         1
MAYOTTE                              1
ANGOLA                               1
FALKLAND ISLANDS                     1
CYPRUS                               1
NORTHERN MARIANA ISLANDS             1
PARAGUAY                             1
NEVIS                                1
MALDIVE ISLANDS                      1
MID-PACIFC OCEAN                     1
NORTHERN ARABIAN SEA                 1
PUERTO RICO                          1
ANTIGUA                              1
ARUBA                                1
INDIAN OCEAN?                        1
TUVALU                               1
BANGLADESH                           1
COOK ISLANDS                         1
OCEAN                                1
SUDAN?                               1
BRITISH NEW GUINEA                   1
RED SEA                              1
KUWAIT                               1
FEDERATED STATES OF MICRONESIA       1
NETHERLANDS ANTILLES                 1
CURACAO                              1
GEORGIA                              1
ARGENTINA                            1
BAY OF BENGAL                        1
JAVA                                 1
GABON                                1
SAN DOMINGO                          1
GUATEMALA                            1
SOLOMON ISLANDS / VANUATU            1
IRELAND                              1
NORTH SEA                            1
BETWEEN PORTUGAL & INDIA             1
GULF OF ADEN                         1
Name: Country, dtype: int64

In [44]:
test.isnull().sum()

43

In [45]:
df["Country"] = test

In [46]:
df["Country"].value_counts()

USA                               2116
AUSTRALIA                         1279
SOUTH AFRICA                       565
PAPUA NEW GUINEA                   133
NEW ZEALAND                        125
BRAZIL                             102
BAHAMAS                             98
MEXICO                              81
ITALY                               71
FIJI                                65
PHILIPPINES                         60
REUNION                             57
NEW CALEDONIA                       51
MOZAMBIQUE                          44
CUBA                                42
SPAIN                               40
EGYPT                               39
INDIA                               37
CROATIA                             34
JAPAN                               32
PANAMA                              32
IRAN                                29
SOLOMON ISLANDS                     29
GREECE                              25
HONG KONG                           24
JAMAICA                             23
FRENCH POLYNESIA                    22
INDONESIA                           20
ENGLAND                             19
TONGA                               18
PACIFIC OCEAN                       17
BERMUDA                             16
ATLANTIC OCEAN                      16
SRI LANKA                           14
VANUATU                             14
VIETNAM                             14
FRANCE                              13
MARSHALL ISLANDS                    13
COSTA RICA                          12
SOUTH ATLANTIC OCEAN                12
IRAQ                                12
TURKEY                              12
SENEGAL                             11
VENEZUELA                           11
KENYA                               10
CANADA                              10
NEW GUINEA                          10
UNITED KINGDOM                      10
TAIWAN                               9
COLUMBIA                             9
SIERRA LEONE                         9
TANZANIA                             8
SCOTLAND                             8
SEYCHELLES                           8
CHILE                                8
ECUADOR                              8
CARIBBEAN SEA                        8
SOUTH KOREA                          8
MAURITIUS                            7
DOMINICAN REPUBLIC                   7
NORTH PACIFIC OCEAN                  7
INDIAN OCEAN                         7
MADAGASCAR                           7
ISRAEL                               7
YEMEN                                7
SAMOA                                7
OKINAWA                              6
CHINA                                6
SOMALIA                              6
NEW BRITAIN                          6
SINGAPORE                            6
NICARAGUA                            6
THAILAND                             6
KIRIBATI                             6
TURKS & CAICOS                       5
SAUDI ARABIA                         5
MALTA                                5
MID ATLANTIC OCEAN                   5
BARBADOS                             5
LIBYA                                5
PALAU                                5
AZORES                               5
EL SALVADOR                          4
RUSSIA                               4
BURMA                                4
MALAYSIA                             4
GUAM                                 4
NIGERIA                              4
PERSIAN GULF                         4
NORTH ATLANTIC OCEAN                 4
GRENADA                              4
SUDAN                                4
HAITI                                3
UNITED ARAB EMIRATES                 3
BELIZE                               3
CAPE VERDE                           3
PORTUGAL                             3
HONDURAS                             3
AMERICAN SAMOA                       3
LEBANON                              3
MICRONESIA                           3
LIBERIA                              3
TUNISIA                              3
MONTENEGRO                           3
GUINEA                               3
URUGUAY                              3
TRINIDAD & TOBAGO                    3
YEMEN                                2
PACIFIC OCEAN                        2
CRETE                                2
JOHNSTON ISLAND                      2
SOUTHWEST PACIFIC OCEAN              2
NAMIBIA                              2
NORWAY                               2
MEDITERRANEAN SEA                    2
CAYMAN ISLANDS                       2
SOUTH PACIFIC OCEAN                  2
CENTRAL PACIFIC                      2
SLOVENIA                             1
ICELAND                              1
BAHREIN                              1
NICARAGUA                            1
GHANA                                1
WESTERN SAMOA                        1
RED SEA / INDIAN OCEAN               1
COAST OF AFRICA                      1
SOUTH CHINA SEA                      1
SYRIA                                1
DJIBOUTI                             1
GREENLAND                            1
THE BALKANS                          1
ITALY / CROATIA                      1
ASIA?                                1
MEDITERRANEAN SEA?                   1
ST HELENA                            1
MEXICO                               1
ALGERIA                              1
BRITISH WEST INDIES                  1
IRAN / IRAQ                          1
EQUATORIAL GUINEA / CAMEROON         1
MONACO                               1
RED SEA?                             1
BRITISH VIRGIN ISLANDS               1
ST. MAARTIN                          1
ADMIRALTY ISLANDS                    1
TASMAN SEA                           1
GRAND CAYMAN                         1
SWEDEN                               1
NORTH ATLANTIC OCEAN                 1
PALESTINIAN TERRITORIES              1
KOREA                                1
ANDAMAN / NICOBAR ISLANDAS           1
ST. MARTIN                           1
GUYANA                               1
MARTINIQUE                           1
BRITISH ISLES                        1
DIEGO GARCIA                         1
MAYOTTE                              1
ANGOLA                               1
FALKLAND ISLANDS                     1
CYPRUS                               1
NORTHERN MARIANA ISLANDS             1
PARAGUAY                             1
NEVIS                                1
MALDIVE ISLANDS                      1
MID-PACIFC OCEAN                     1
NORTHERN ARABIAN SEA                 1
PUERTO RICO                          1
ANTIGUA                              1
ARUBA                                1
INDIAN OCEAN?                        1
TUVALU                               1
BANGLADESH                           1
COOK ISLANDS                         1
OCEAN                                1
SUDAN?                               1
BRITISH NEW GUINEA                   1
RED SEA                              1
KUWAIT                               1
FEDERATED STATES OF MICRONESIA       1
NETHERLANDS ANTILLES                 1
CURACAO                              1
GEORGIA                              1
ARGENTINA                            1
BAY OF BENGAL                        1
JAVA                                 1
GABON                                1
SAN DOMINGO                          1
GUATEMALA                            1
SOLOMON ISLANDS / VANUATU            1
IRELAND                              1
NORTH SEA                            1
BETWEEN PORTUGAL & INDIA             1
GULF OF ADEN                         1
Name: Country, dtype: int64

## IV Year

In [47]:
test = df["Year"]

In [48]:
test = df["Year"].replace(0, "NA")

In [49]:
test.value_counts()

2015    139
2011    128
2014    125
NA      124
2013    122
2008    121
2009    120
2012    117
2007    112
2016    103
2006    103
2005    103
2010    101
2000     97
1959     93
1960     93
2003     92
2004     92
2001     92
2002     88
1962     86
1961     78
1995     76
1964     66
1999     65
1998     65
1996     61
1963     61
1966     58
1997     57
1992     56
1994     56
1993     56
1988     55
1958     54
1989     53
1956     51
1965     51
1983     50
1975     49
1981     49
1967     48
1968     46
1955     43
1950     43
1970     42
1954     42
1942     41
1957     41
1984     41
1982     40
1976     39
1986     39
1990     38
1991     38
1974     38
1929     37
1985     37
1953     36
1980     35
1987     35
1972     35
1935     32
1951     31
1949     31
1944     31
1936     30
1937     30
1947     30
1969     30
1948     29
1952     29
1931     29
1943     28
1971     28
1932     27
1941     27
1973     27
1934     27
1946     26
1928     26
1930     26
1977     26
1916     25
1978     25
1979     25
1938     24
1939     24
1940     24
1907     23
1922     22
1933     22
1926     21
1906     21
1923     21
1895     20
1924     19
1927     19
1898     19
1899     19
1909     18
1914     17
1945     16
1905     16
1890     16
1911     16
1913     16
1888     15
1886     15
1894     15
1902     15
1920     15
1880     15
1910     14
1877     14
1919     14
1925     14
1893     13
1900     13
1904     13
1908     13
1912     13
1862     12
1887     12
1915     12
1878     12
1897     11
1882     11
1921     11
1892     11
1917     11
1896     11
1874     10
1852     10
1883     10
1903     10
1881      9
1885      9
1889      9
1901      9
1879      8
1876      8
1891      8
1871      8
1870      8
1864      8
1855      7
1863      7
1853      7
1872      7
1868      6
1860      6
1847      6
1884      6
1849      6
1918      5
1861      5
1875      5
1827      4
1840      4
1817      4
1844      4
1845      4
1839      4
1867      4
1865      4
1856      4
1873      4
1858      4
1700      3
1826      3
1830      3
1837      3
1851      3
1842      3
1848      3
1776      2
1829      2
1642      2
1869      2
1825      2
1828      2
1832      2
1835      2
1836      2
1755      1
1758      1
1703      1
1749      1
1764      1
1748      1
1742      1
1738      1
1733      1
1721      1
1543      1
77        1
1638      1
1554      1
1617      1
1595      1
1767      1
500       1
1580      1
1555      1
1637      1
1803      1
1771      1
1816      1
1854      1
1846      1
1859      1
1841      1
1866      1
1834      1
1831      1
1822      1
1819      1
1818      1
1812      1
1779      1
1811      1
1807      1
1805      1
1804      1
1850      1
1800      1
1791      1
1788      1
1787      1
1785      1
5         1
Name: Year, dtype: int64

In [50]:
test.isnull().value_counts()

False    5992
Name: Year, dtype: int64

In [51]:
test.value_counts()

2015    139
2011    128
2014    125
NA      124
2013    122
2008    121
2009    120
2012    117
2007    112
2016    103
2006    103
2005    103
2010    101
2000     97
1959     93
1960     93
2003     92
2004     92
2001     92
2002     88
1962     86
1961     78
1995     76
1964     66
1999     65
1998     65
1996     61
1963     61
1966     58
1997     57
1992     56
1994     56
1993     56
1988     55
1958     54
1989     53
1956     51
1965     51
1983     50
1975     49
1981     49
1967     48
1968     46
1955     43
1950     43
1970     42
1954     42
1942     41
1957     41
1984     41
1982     40
1976     39
1986     39
1990     38
1991     38
1974     38
1929     37
1985     37
1953     36
1980     35
1987     35
1972     35
1935     32
1951     31
1949     31
1944     31
1936     30
1937     30
1947     30
1969     30
1948     29
1952     29
1931     29
1943     28
1971     28
1932     27
1941     27
1973     27
1934     27
1946     26
1928     26
1930     26
1977     26
1916     25
1978     25
1979     25
1938     24
1939     24
1940     24
1907     23
1922     22
1933     22
1926     21
1906     21
1923     21
1895     20
1924     19
1927     19
1898     19
1899     19
1909     18
1914     17
1945     16
1905     16
1890     16
1911     16
1913     16
1888     15
1886     15
1894     15
1902     15
1920     15
1880     15
1910     14
1877     14
1919     14
1925     14
1893     13
1900     13
1904     13
1908     13
1912     13
1862     12
1887     12
1915     12
1878     12
1897     11
1882     11
1921     11
1892     11
1917     11
1896     11
1874     10
1852     10
1883     10
1903     10
1881      9
1885      9
1889      9
1901      9
1879      8
1876      8
1891      8
1871      8
1870      8
1864      8
1855      7
1863      7
1853      7
1872      7
1868      6
1860      6
1847      6
1884      6
1849      6
1918      5
1861      5
1875      5
1827      4
1840      4
1817      4
1844      4
1845      4
1839      4
1867      4
1865      4
1856      4
1873      4
1858      4
1700      3
1826      3
1830      3
1837      3
1851      3
1842      3
1848      3
1776      2
1829      2
1642      2
1869      2
1825      2
1828      2
1832      2
1835      2
1836      2
1755      1
1758      1
1703      1
1749      1
1764      1
1748      1
1742      1
1738      1
1733      1
1721      1
1543      1
77        1
1638      1
1554      1
1617      1
1595      1
1767      1
500       1
1580      1
1555      1
1637      1
1803      1
1771      1
1816      1
1854      1
1846      1
1859      1
1841      1
1866      1
1834      1
1831      1
1822      1
1819      1
1818      1
1812      1
1779      1
1811      1
1807      1
1805      1
1804      1
1850      1
1800      1
1791      1
1788      1
1787      1
1785      1
5         1
Name: Year, dtype: int64

In [52]:
test.isnull().sum()

0

In [53]:
test = test.astype('object')

In [54]:
type(test)

pandas.core.series.Series

In [55]:
test.value_counts()

2015    139
2011    128
2014    125
NA      124
2013    122
2008    121
2009    120
2012    117
2007    112
2016    103
2006    103
2005    103
2010    101
2000     97
1959     93
1960     93
2003     92
2004     92
2001     92
2002     88
1962     86
1961     78
1995     76
1964     66
1999     65
1998     65
1996     61
1963     61
1966     58
1997     57
1992     56
1994     56
1993     56
1988     55
1958     54
1989     53
1956     51
1965     51
1983     50
1975     49
1981     49
1967     48
1968     46
1955     43
1950     43
1970     42
1954     42
1942     41
1957     41
1984     41
1982     40
1976     39
1986     39
1990     38
1991     38
1974     38
1929     37
1985     37
1953     36
1980     35
1987     35
1972     35
1935     32
1951     31
1949     31
1944     31
1936     30
1937     30
1947     30
1969     30
1948     29
1952     29
1931     29
1943     28
1971     28
1932     27
1941     27
1973     27
1934     27
1946     26
1928     26
1930     26
1977     26
1916     25
1978     25
1979     25
1938     24
1939     24
1940     24
1907     23
1922     22
1933     22
1926     21
1906     21
1923     21
1895     20
1924     19
1927     19
1898     19
1899     19
1909     18
1914     17
1945     16
1905     16
1890     16
1911     16
1913     16
1888     15
1886     15
1894     15
1902     15
1920     15
1880     15
1910     14
1877     14
1919     14
1925     14
1893     13
1900     13
1904     13
1908     13
1912     13
1862     12
1887     12
1915     12
1878     12
1897     11
1882     11
1921     11
1892     11
1917     11
1896     11
1874     10
1852     10
1883     10
1903     10
1881      9
1885      9
1889      9
1901      9
1879      8
1876      8
1891      8
1871      8
1870      8
1864      8
1855      7
1863      7
1853      7
1872      7
1868      6
1860      6
1847      6
1884      6
1849      6
1918      5
1861      5
1875      5
1827      4
1840      4
1817      4
1844      4
1845      4
1839      4
1867      4
1865      4
1856      4
1873      4
1858      4
1700      3
1826      3
1830      3
1837      3
1851      3
1842      3
1848      3
1776      2
1829      2
1642      2
1869      2
1825      2
1828      2
1832      2
1835      2
1836      2
1755      1
1758      1
1703      1
1749      1
1764      1
1748      1
1742      1
1738      1
1733      1
1721      1
1543      1
77        1
1638      1
1554      1
1617      1
1595      1
1767      1
500       1
1580      1
1555      1
1637      1
1803      1
1771      1
1816      1
1854      1
1846      1
1859      1
1841      1
1866      1
1834      1
1831      1
1822      1
1819      1
1818      1
1812      1
1779      1
1811      1
1807      1
1805      1
1804      1
1850      1
1800      1
1791      1
1788      1
1787      1
1785      1
5         1
Name: Year, dtype: int64

## V Sex

In [56]:
no = df["Sex"]

In [57]:
no

Orginal_Order
1       M
2       M
3       M
4       M
5       M
       ..
5988    M
5989    M
5990    M
5991    M
5992    M
Name: Sex, Length: 5992, dtype: object

In [58]:
no.isnull().sum()

567

In [59]:
no.value_counts()

M      4835
F       585
M         2
N         1
.         1
lli       1
Name: Sex, dtype: int64

In [60]:
no = no.replace( [np.nan, "M ", ".", "N", "lli"   ],
                  ["NA", "M", "NA", "NA" , "NA" ])

In [61]:
no.value_counts()

M     4837
F      585
NA     570
Name: Sex, dtype: int64

In [62]:
test = df["Date"]

In [63]:
test.value_counts()

1957                                                                11
1942                                                                 9
1956                                                                 8
1941                                                                 7
1950                                                                 7
1958                                                                 7
No date                                                              6
1949                                                                 6
Oct-60                                                               5
28-Jul-95                                                            5
1954                                                                 5
1955                                                                 5
No date, Before 1963                                                 5
12-Apr-01                                                            5
05-Oct-03                                                            5
Aug-56                                                               5
1959                                                                 5
1970s                                                                5
1940                                                                 5
23-Jan-70                                                            4
20-Sep-15                                                            4
1876                                                                 4
14-Jun-12                                                            4
Before 1958                                                          4
09-Jul-94                                                            4
Before 1906                                                          4
1945                                                                 4
1898                                                                 4
1995                                                                 4
1960s                                                                4
1890                                                                 4
1952                                                                 4
28-Dec-14                                                            4
1938                                                                 4
27-Jul-52                                                            4
Reported 10-Oct-1906                                                 4
1960                                                                 4
27-Dec-08                                                            4
09-Jan-10                                                            4
1961                                                                 4
18-May-10                                                            3
31-Oct-03                                                            3
1930                                                                 3
Mar-53                                                               3
1982                                                                 3
1941-1945                                                            3
07-Jul-12                                                            3
26-Jun-08                                                            3
1929                                                                 3
24-Jun-03                                                            3
08-Sep-00                                                            3
26-Jul-1885                                                          3
1700s                                                                3
25-Jun-13                                                            3
28-Dec-61                                                            3
16-Aug-74                                                            3
Jul-03                                                               3
11-Aug-97                                                            3
18-Aug-01                                                            3
30-Sep-07                                                            3
14-Sep-03                                                            3
01-Apr-34                                                            3
Before 1921                                                          3
1971                                                                 3
19-Aug-01                                                            3
08-Mar-92                                                            3
 01-Sep-2013                                                         3
1904                                                                 3
1998                                                                 3
1926                                                                 3
17-Oct-15                                                            3
30-Aug-08                                                            3
11-Jun-62                                                            3
07-Jul-16                                                            3
Before 1962                                                          3
Before 1911                                                          3
1940 - 1950                                                          3
1913                                                                 3
28-Mar-08                                                            3
1923                                                                 3
26-Jun-12                                                            3
17-Aug-11                                                            3
1948                                                                 3
31-Dec-99                                                            3
01-Jun-14                                                            3
1953                                                                 3
1883                                                                 3
1968                                                                 3
31-May-97                                                            3
27-Aug-14                                                            3
27-Jul-04                                                            3
20-May-66                                                            3
19-Aug-07                                                            3
13-Mar-77                                                            3
20-Aug-06                                                            3
1939                                                                 3
06-Apr-05                                                            3
27-Sep-02                                                            3
Apr-60                                                               3
1946                                                                 3
Jul-06                                                               3
28-Jun-08                                                            3
14-May-14                                                            3
20-Apr-03                                                            3
09-Feb-96                                                            3
18-Sep-16                                                            3
1973                                                                 3
Before 2012                                                          3
12-Jul-16                                                            3
16-May-98                                                            3
28-Jul-13                                                            3
11-Apr-01                                                            3
02-Sep-12                                                            3
1943                                                                 3
24-Jun-15                                                            3
29-Aug-82                                                            3
06-Mar-09                                                            3
11-Jan-62                                                            3
25-Nov-05                                                            3
08-Aug-1899                                                          3
07-Jan-74                                                            3
22-May-04                                                            3
14-Jan-62                                                            3
06-Jan-61                                                            3
24-Jan-09                                                            3
24-Jul-09                                                            3
26-Jun-15                                                            3
May-Jun-1965                                                         3
09-Jun-14                                                            3
18-Mar-14                                                            3
Nov-60                                                               3
15-Jun-83                                                            2
13-Apr-04                                                            2
17-Jan-59                                                            2
02-Jun-16                                                            2
16-Aug-11                                                            2
24-Aug-05                                                            2
16-Apr-32                                                            2
Reported 15-Jun-1894                                                 2
20-Dec-63                                                            2
23-Oct-26                                                            2
18-Jul-46                                                            2
31-Aug-13                                                            2
Mar-55                                                               2
Jun-65                                                               2
Jul-64                                                               2
07-Jan-62                                                            2
29-May-98                                                            2
28-Apr-08                                                            2
Oct-61                                                               2
08-Jul-06                                                            2
Reported 26-Jun-1972                                                 2
26-Jul-15                                                            2
Dec-96                                                               2
18-Jul-07                                                            2
18-Jan-12                                                            2
21-Jun-78                                                            2
01-Jan-64                                                            2
16-Mar-13                                                            2
22-Jan-54                                                            2
26-Dec-63                                                            2
15-Aug-59                                                            2
05-Oct-14                                                            2
13-Feb-74                                                            2
16-Apr-91                                                            2
08-Apr-79                                                            2
14-Nov-47                                                            2
29-Jan-92                                                            2
23-Apr-03                                                            2
Reported 15-Mar-1897                                                 2
10-Feb-46                                                            2
25-Mar-05                                                            2
28-Oct-97                                                            2
15-Jun-16                                                            2
02-Jul-04                                                            2
23-May-13                                                            2
1944                                                                 2
05-Jul-03                                                            2
26-Apr-08                                                            2
10-Jul-02                                                            2
20-Jan-89                                                            2
06-Mar-12                                                            2
14-Mar-12                                                            2
23-May-04                                                            2
01-Jun-08                                                            2
26-Nov-91                                                            2
07-Jul-11                                                            2
02-Apr-83                                                            2
05-Apr-71                                                            2
23-Mar-94                                                            2
22-Jul-09                                                            2
23-Jun-75                                                            2
18-Oct-12                                                            2
19-Nov-75                                                            2
01-Mar-09                                                            2
05-Jul-14                                                            2
11-Jan-09                                                            2
13-May-11                                                            2
30-Nov-10                                                            2
Reported 06-Jul-1915                                                 2
16-Apr-05                                                            2
16-Jul-16                                                            2
24-Jul-08                                                            2
26-Jul-16                                                            2
24-Sep-11                                                            2
25-Jun-10                                                            2
12-Mar-76                                                            2
27-Nov-21                                                            2
19-Dec-59                                                            2
08-Sep-12                                                            2
05-Oct-15                                                            2
Nov-99                                                               2
19-Sep-48                                                            2
Ca. 1950                                                             2
Mid-Aug-1886                                                         2
14-Apr-88                                                            2
Jul-43                                                               2
04-Jul-00                                                            2
14-Aug-97                                                            2
02-Sep-05                                                            2
30-Jul-75                                                            2
21-Aug-00                                                            2
04-Jul-15                                                            2
Reported 27-Aug-1913                                                 2
18-Jun-14                                                            2
30-Sep-82                                                            2
22-Aug-88                                                            2
17-Jul-05                                                            2
1950s                                                                2
30-Aug-55                                                            2
1853                                                                 2
02-Sep-06                                                            2
05-Sep-16                                                            2
04-Apr-65                                                            2
02-Oct-54                                                            2
09-Apr-06                                                            2
30-Mar-87                                                            2
14-Oct-72                                                            2
30-Sep-84                                                            2
10-Sep-00                                                            2
13-Sep-03                                                            2
Fall 1943                                                            2
12-Nov-03                                                            2
09-Aug-14                                                            2
Sep-56                                                               2
09-Apr-59                                                            2
Apr-53                                                               2
10-Aug-10                                                            2
1989                                                                 2
03-Apr-60                                                            2
07-Feb-82                                                            2
03-Jan-61                                                            2
01-Aug-98                                                            2
30-Oct-90                                                            2
10-Nov-15                                                            2
31-Aug-95                                                            2
Aug-67                                                               2
Before 1903                                                          2
19-Jun-11                                                            2
Jun-35                                                               2
25-Apr-96                                                            2
 25-Aug-2013                                                         2
24-Aug-81                                                            2
09-Oct-15                                                            2
10-May-08                                                            2
Ca. 1880                                                             2
1937                                                                 2
02-Sep-96                                                            2
26-Jan-89                                                            2
10-May-90                                                            2
25-Jul-85                                                            2
06-Oct-00                                                            2
23-Sep-55                                                            2
04-Jul-88                                                            2
26-Aug-95                                                            2
Before 1871                                                          2
13-Jul-16                                                            2
Reported 13-Jun-2002                                                 2
12-Aug-54                                                            2
World War II                                                         2
Sep-86                                                               2

In [64]:
#test = test.replace("Reported ", "")

In [65]:
#test.value_counts()

In [66]:
test = pd.to_datetime(test, errors = "coerce")

In [67]:
test.isnull().sum()

857

In [68]:
test.value_counts().sum()

5135

In [71]:
test = pd.to_datetime(df1["Date"], errors = "coerce")

In [86]:
df["Date"] = test

In [87]:
df

,Case_Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal,Time,Species,Investigator_or_Source,Source
Orginal_Order,,,,,,,,,,,,,,,,,
1,ND.0001,NaT,0,Unprovoked,SRI LANKA,Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away the lower extremities""",Y,NaN,NaN,S.W. Baker,ND-0001-Ceylon.pdf
2,ND.0002,NaT,0,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,Jules Patterson,M,NaN,FATAL,Y,NaN,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf
3,ND.0003,NaT,0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,NaN,FATAL,Y,NaN,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf
4,ND.0004,NaT,0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf
5,ND.0005,NaT,0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5988,2016.09.15,2016-09-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,male,M,NaN,No injury: Knocked off board by shark,N,NaN,2 m shark,"The Age, 9/16/2016",2016.09.16-BellsBeach.pdf
5989,2016.09.17,2016-09-17,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,Rory Angiolella,M,NaN,Struck by fin on chest & leg,N,NaN,NaN,"The Age, 9/18/2016",2016.09.17-Angiolella.pdf
5990,2016.09.18.a,2016-09-18,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,43,Lacerations to lower leg,N,10h43,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.a-NSB.pdf
5991,2016.09.18.b,2016-09-18,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Chucky Luciano,M,36,Lacerations to hands,N,11h00,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.b-Luciano.pdf
5992,2016.09.18.c,2016-09-18,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,16,Minor injury to thigh,N,13h00,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.c-NSB.pdf

In [74]:
#df1.dropna(axis = 'index' , subset = df1["Date"])

In [75]:
#df1["Date"] = df1.index.values               
#df1 = df1[df1.Date.notnull()]                  
#df1.drop(["Date"], axis=1, inplace=True).copy

In [88]:
#reg = df["Date"].replace("(.)" , "(\d{2}[-][\d\D]{2,3}[-]\d{2,4})", regex=True)
import re

In [78]:
#pat_old = re.compile("(.)")

In [79]:
#pat_old

In [80]:
#type(pat_old)

In [81]:
#pat_new = re.compile(r'(\d{2}[-][\d\D]{2,3}[-]\d{2,4})')

In [82]:
#type(pat_new)

In [83]:
#type(pat_new)

In [84]:
#reg = df["Date"].replace(pat_old , pat_new, regex=True)

In [85]:
#reg

In [89]:
df

,Case_Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal,Time,Species,Investigator_or_Source,Source
Orginal_Order,,,,,,,,,,,,,,,,,
1,ND.0001,NaT,0,Unprovoked,SRI LANKA,Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away the lower extremities""",Y,NaN,NaN,S.W. Baker,ND-0001-Ceylon.pdf
2,ND.0002,NaT,0,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,Jules Patterson,M,NaN,FATAL,Y,NaN,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf
3,ND.0003,NaT,0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,NaN,FATAL,Y,NaN,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf
4,ND.0004,NaT,0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf
5,ND.0005,NaT,0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5988,2016.09.15,2016-09-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,male,M,NaN,No injury: Knocked off board by shark,N,NaN,2 m shark,"The Age, 9/16/2016",2016.09.16-BellsBeach.pdf
5989,2016.09.17,2016-09-17,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,Rory Angiolella,M,NaN,Struck by fin on chest & leg,N,NaN,NaN,"The Age, 9/18/2016",2016.09.17-Angiolella.pdf
5990,2016.09.18.a,2016-09-18,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,43,Lacerations to lower leg,N,10h43,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.a-NSB.pdf
5991,2016.09.18.b,2016-09-18,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Chucky Luciano,M,36,Lacerations to hands,N,11h00,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.b-Luciano.pdf
5992,2016.09.18.c,2016-09-18,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,16,Minor injury to thigh,N,13h00,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.c-NSB.pdf